spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

data:
  redirectUri: http://localhost:8080/
  clientId: devLocal
  secret: younIrtyij3
  servidorOauth: cas.staging.iti.br/oauth2.0
  assinaturaApiUri: https://assinatura-api.staging.iti.br/externo/v2/