spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: optional:file:.env[.properties]
server:
  port : ${SERVER_PORT}
govbr:
  redirectUri: ${REDIRECT_URI}
  clientId: ${CLIENT_ID}
  secret: ${SECRET}
  servidorOauth: ${SERVIDOR_OAUTH}
  assinaturaApiUri: ${ASSINATURA_API_URI}